#!/bin/bash

function udp_all_ports {
  echo ""
  echo "            *********************************************************************"
  echo "            |                                                                   |"
  echo "            |               Now starting a UDP all ports scan!                  |"
  echo "            |                                                                   |"
  echo "            *********************************************************************"
  echo ""
}

udp_all_ports

function next_host {
  printf "\n"
  printf "*************************************************"
  printf "       ${GREEN}Starting next host!${RESET}       "
  printf "*************************************************"
  printf "\n"
}


for ip in $(cat /root/exam/oscp_tools/iplist.txt); do
  printf "\n"
  printf "${RED}[+]${RESET} ${BLUE}UDP nmap scan for $ip...${RESET}\n"
  printf "\n"
  nmap -sU -vv -Pn --stats-every 3m --max-retries 2 -oX /root/exam/hosts/$ip/nmap_scans/udp-scan.xml $ip && xsltproc /root/exam/hosts/$ip/nmap_scans/udp-scan.xml \
  -o /root/exam/hosts/$ip/nmap_scans/udp-scan-report.html

  sleep 2;

  firefox /root/exam/hosts/$ip/nmap_scans/udp-scan-report.html

  next_host

  done

  exit